### ISSUE TITLE
Remove TLS1.0 and TLS1.1

### ISSUE THREAD

**Issue by wol-win** [damalis/full-stack-nginx-wordpress-for-everyone-with-docker-compose#5]
The current configuration for the nginx webserver includes the TLS1.0 and TLS1.1 protocols. These are not recommended anymore, the minimum level should be TLS1.2.

Therefore, a removal of TLS1.0 and TLS1.1 in the options file is strongly advised.

**Comment by damalis** [comment]
thanks @wol-win 

 fixed issue
