### ISSUE TITLE
Container certbot

### ISSUE THREAD

**Issue by ersandrino** [damalis/full-stack-nginx-wordpress-for-everyone-with-docker-compose#6]
Hello, and congratulations on the creation of this "all in one" product. I have used it several times and it has helped me a lot. After your update, I'm having a problem through the automatic installation. After having entered everything necessary, my small Debian 12 server with a very basic configuration (2 cores and 2GB of Ram) gives me this error: dependency failed to start: container certbot is unhealthy stopping on installation. My dockers all started correctly....but the installation doesn't reach the end. Do you have any suggestions?
![Screenshot_2](https://github.com/damalis/full-stack-nginx-wordpress-for-everyone-with-docker-compose/assets/43796939/ec476a35-dc32-447f-b82a-0ef1daed0e88)

**Comment by damalis** [comment]
Hi;

- I tried and don't get any problem.
- You must exec `docker logs certbot` to see the problem details 
- You could add "--staging" flag after "certbot certonly" in "docker-compose.yml" file for sandbox

**Comment by ersandrino** [comment]
Hi, sorry if I'm only replying now but I've been very busy. I solved it thanks to your suggestion. Thank you very much. You were really kind!
