### ISSUE TITLE
possbile to add nginx proxy manager?

### ISSUE THREAD

**Issue by mnm000** [damalis/full-stack-nginx-wordpress-for-everyone-with-docker-compose#8]
Thank you so much! great work!

is possbile to add nginx proxy manager?

**Comment by damalis** [comment]
Thanks.

Yes, possible.

**Comment by mnm000** [comment]
include in any future update? would be wonderful.. once again thank you my wordpress site is petty fast..

**Comment by damalis** [comment]
The possible has been real [here](https://github.com/damalis/full-stack-nginx-proxy-manager-for-everyone-with-damalis-repository)

**Comment by mnm000** [comment]
The best!!!! thank you so much!!!
